name: Check for Branch Drift (Main vs Dev)

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  drift-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Check for drift and create PR if necessary
        run: |
          if git diff --quiet dev main; then
            echo "No drift detected between dev and main branches."
          else
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Actions"
            git checkout main
            git pull origin main
            git checkout dev
            git pull origin dev
            git checkout -b dev
            # git merge main --no-ff --no-edit
            # git push origin dev_to_main
            gh pr create --draft --base main --head dev_to_main --title "Merge dev into main" --body "Automatically created pull request to merge dev into main due to drift detection."
          fi
