name: Check for Branch Drift (Main vs Dev)

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  drift-check:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check for Main Branch Diff
        run: |
          git branch -v
          git fetch origin dev
          GIT_DIFF=$(git diff main dev)
          if [[ -z "${GIT_DIFF}" ]]; then
            echo "main is up to date with all commits from dev"
          else
            PR_OUTPUT=$(gh pr list --base main --head dev 2>&1)
            # Check the exit code of the gh pr list command
            if [ $? -eq 0 ]; then
              # If exit code is 0 (no errors), check for empty output (no PRs)
              if [[ -z "$PR_OUTPUT" ]]; then
                echo "No PR found"  # No PR found
                gh pr create --draft --title "Drift Detected base:main and head:dev" -b "Detected drift between base main branch and head dev branches"  # Create a draft PR with details
              else
                echo "A PR from head:dev to base:main already exists!" # PR(s) found
              fi
            else
              echo "false"  # Error occurred during PR listing (likely not relevant for existence check)
            fi
          fi
    env:
      GITHUB_TOKEN: ${{ github.token }}
