name: Check for Branch Drift (Main vs Dev)

on: push
  # schedule:
  #   - cron: "*/15 * * * *"

jobs:
  drift-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for Main Branch Diff
        run: |
          git fetch origin main:main  # Fetch latest main branch
          main_branch_sha=$(git rev-parse origin/main)
          dev_branch_sha=$(git rev-parse HEAD)
          if [ "$main_branch_sha" != "$dev_branch_sha" ]; then
            git diff --name-only main HEAD > drift_diff.txt  # Capture differences in a file
            if [ -s drift_diff.txt ]; then  # Check if there's a diff
              DIFF_CONTENT=$(cat drift_diff.txt)
              gh auth login
              gh pr create --draft --title "Potential Drift Detected (dev: $dev_branch_sha)" -b "Detected drift in: $DIFF_CONTENT"  # Create a draft PR with details
              rm drift_diff.txt  # Clean up the temporary file
            fi
          fi
    # env:
    #   GITHUB_TOKEN: ${{ secrets.token }}
